theme: jekyll-theme-cayman

title: "Bruno Garbuio De Souza | Portfolio"
description: "Showcasing my projects, experience, and journey in software development."

# Add a favicon (optional)
favicon: /assets/images/icons8-tech-16.ico

# Customize colors (optional)
show_downloads: false  
