title: "Bruno Garbuio De Souza | Portfolio"
description: "Showcasing my projects, experience, and journey in software development."

# Theme selection
theme: jekyll-theme-primer

# Favicon (optional)
favicon: /assets/images/icons8-tech-16.ico

# Customize appearance (optional)
show_downloads: false

github:
  is_project_page: false

footer_links: []  # Removes default footer links from the theme

plugins:
  - jekyll-seo-tag


# Author Information
author:
  name: "Bruno Garbuio De Souza"
  email: "23bdesouza@gmail.com"

# Social Media Links
social_links:
  linkedin: "https://www.linkedin.com/in/bruno-garbuio-de-souza"
  github: "https://github.com/brunogdzz"
  email: "23bdesouza@gmail.com"

# Logo (optional)
logo: /assets/images/icons8-tech-16.ico

# Show Archives
show_archives: true

# Pagination for Posts
paginate: 5

# Enable/Disable Search
enable_search: true

# Enable/Disable Categories
show_categories: true

# Customize Colors (optional)
colors:
  primary: "#FF6347" # Red/orange color for accents
  secondary: "#333333" # Dark background for content
  background: "#FFFFFF" # Light background

# Exclude Pages from Navigation (optional)
exclude:
  - "README.md"
  - "LICENSE.md"

